name: File Upload Handler

on:
  push:
    branches:
      - main
    paths:
      - 'uploads/**'

jobs:
  handle-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Process uploaded files
      run: |
        # 这里可以添加自定义处理逻辑
        echo "文件已成功接收！"
